### ISSUE TITLE
BROKEN LINK - Incorrect URL in repo description

### ISSUE THREAD

**Issue by xadhix** [jackpal/Dandy-Dungeon#1]
The URL in the description of the repo is incomplete. Leads to http://dandydungeon/ instead of http://www.dandydungeon.com/

**Comment by jackpal** [comment]
Thanks! I fixed the link to point to the JavaScript demo web page.

FWIW http://www.dandydungeon.com/ is an unrelated (much newer) game with the same name.

**Comment by MonsMarineris** [comment]
Jack Palevich, just wanted to tell you I love Dandy and the legacy it built. You're awesome!
